<a href="https://colab.research.google.com/github/Karthik5412/wardrobe_cnn/blob/main/ann_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np

In [60]:
df = pd.read_csv('/content/drive/MyDrive/Deep_Learning/custumes/color_combinations_60000_rgb.csv')
df.head()

,Shirt_Color,Shirt_RGB_R,Shirt_RGB_G,Shirt_RGB_B,Pants_Color,Pants_RGB_R,Pants_RGB_G,Pants_RGB_B,Shoes_Color,Shoes_RGB_R,Shoes_RGB_G,Shoes_RGB_B,Vibe,Match_Score
0,Maroon,216,127,167,Mustard Pants,209,199,247,Cognac Leather,230,181,255,Casual Everyday,5
1,Light Pink,219,80,210,Blue Denim,180,146,201,Chocolate Suede,27,146,31,Casual Everyday,5
2,Rust Orange,91,60,204,Copper Pants,155,2,6,Olive Sneakers,213,80,253,Casual Everyday,5
3,Celadon,64,243,128,Tobacco Pants,105,63,124,Chocolate Suede,27,146,31,Casual Everyday,5
4,Royal Blue,49,216,149,Khaki,126,194,59,White Sneakers,220,43,27,Casual Everyday,7

In [61]:
unwanted = ["Shirt_Color","Pants_Color", "Shoes_Color", "Vibe"]

df = df.drop(columns=unwanted)
df = df.rename(columns={
    "Shirt_RGB_R" :"Shirt_Red",
    "Shirt_RGB_G" :"Shirt_Green",
    "Shirt_RGB_B" :"Shirt_Blue",
    "Pants_RGB_R" :"Pants_Red",
    "Pants_RGB_G" :"Pants_Green",
    "Pants_RGB_B" :"Pants_Blue",
    "Shoes_RGB_R" :"Shoes_Red",
    "Shoes_RGB_G" :"Shoes_Green",
    "Shoes_RGB_B" :"Shoes_Blue"
})

In [62]:
df.head(2)

,Shirt_Red,Shirt_Green,Shirt_Blue,Pants_Red,Pants_Green,Pants_Blue,Shoes_Red,Shoes_Green,Shoes_Blue,Match_Score
0,216,127,167,209,199,247,230,181,255,5
1,219,80,210,180,146,201,27,146,31,5

In [63]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [64]:
scaled_df = scale.fit_transform(df.drop(columns='Match_Score'))
final_df = df['Match_Score']

In [65]:
from sklearn.model_selection import train_test_split

x_train,x_test, y_train, y_test = train_test_split(scaled_df,val_df,test_size=0.2,random_state= 42)

In [66]:
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import Sequential

In [67]:
ann = Sequential([
    Dense(128,activation='relu', input_shape=(x_train.shape[1],)),
    Dense(64,activation='relu'),
    Dropout(0.3),
    Dense(32, activation='swish'),
    Dropout(0.2),
    Dense(16, activation='swish'),
    Dense(1,activation='softplus')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [68]:
ann.compile(optimizer='adam',loss="mean_squared_error",metrics=['mae'])

In [69]:
from tensorflow.keras.callbacks import EarlyStopping

stops = EarlyStopping(monitor='val_loss', patience=3,restore_best_weights=True)

In [70]:
ann.fit(x_train,y_train,batch_size=64,validation_data=(x_test,y_test),validation_batch_size=64, epochs=50, verbose=1, callbacks=[stops])

Epoch 1/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 1.8468 - mae: 0.8659 - val_loss: 0.5438 - val_mae: 0.4326
Epoch 2/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.5584 - mae: 0.4814 - val_loss: 0.3915 - val_mae: 0.3496
Epoch 3/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.4099 - mae: 0.3839 - val_loss: 0.2940 - val_mae: 0.2542
Epoch 4/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 0.3182 - mae: 0.3021 - val_loss: 0.2268 - val_mae: 0.1937
Epoch 5/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.2724 - mae: 0.2525 - val_loss: 0.1911 - val_mae: 0.1491
Epoch 6/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.2266 - mae: 0.1984 - val_loss: 0.1769 - val_mae: 0.1250
Epoch 7/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.2035 - mae: 0.1645 - val_loss: 0.1764 - val_mae: 0.1289
Epoch 8/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1934 - mae: 0.1529 - val_loss: 0.1706 - val_mae: 0.1154
Epoch 9/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1851 - mae: 0.1492 - val_loss: 0.1595 - val_mae: 0.1332
Epoch 10/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1710 - mae: 0.1468 - val_loss: 0.1515 - val_mae: 0.1070
Epoch 11/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.1598 - mae: 0.1388 - val_loss: 0.1393 - val_mae: 0.1197
Epoch 12/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1474 - mae: 0.1331 - val_loss: 0.1198 - val_mae: 0.0978
Epoch 13/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1275 - mae: 0.1229 - val_loss: 0.1019 - val_mae: 0.1031
Epoch 14/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 0.1086 - mae: 0.1127 - val_loss: 0.0825 - val_mae: 0.0769
Epoch 15/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 0.0936 - mae: 0.1007 - val_loss: 0.0712 - val_mae: 0.0723
Epoch 16/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0853 - mae: 0.0950 - val_loss: 0.0640 - val_mae: 0.0942
Epoch 17/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0775 - mae: 0.0880 - val_loss: 0.0674 - val_mae: 0.0870
Epoch 18/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0716 - mae: 0.0814 - val_loss: 0.0520 - val_mae: 0.0654
Epoch 19/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0683 - mae: 0.0807 - val_loss: 0.0540 - val_mae: 0.0544
Epoch 20/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 0.0614 - mae: 0.0746 - val_loss: 0.0529 - val_mae: 0.0500
Epoch 21/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0584 - mae: 0.0700 - val_loss: 0.0390 - val_mae: 0.0559
Epoch 22/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0478 - mae: 0.0636 - val_loss: 0.0310 - val_mae: 0.0518
Epoch 23/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0424 - mae: 0.0630 - val_loss: 0.0241 - val_mae: 0.0325
Epoch 24/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.0406 - mae: 0.0575 - val_loss: 0.0216 - val_mae: 0.0320
Epoch 25/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.0337 - mae: 0.0516 - val_loss: 0.0199 - val_mae: 0.0448
Epoch 26/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0305 - mae: 0.0486 - val_loss: 0.0214 - val_mae: 0.0282
Epoch 27/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0361 - mae: 0.0525 - val_loss: 0.0180 - val_mae: 0.0330
Epoch 28/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0297 - mae: 0.0469 - val_loss: 0.0188 - val_mae: 0.0483
Epoch 29/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 0.0362 - mae: 0.0522 - val_loss: 0.0199 - val_mae: 0.0428
Epoch 30/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0274 - mae: 0.0441 - val_loss: 0.0125 - val_mae: 0.0149
Epoch 31/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0264 - mae: 0.0428 - val_loss: 0.0215 - val_mae: 0.0338
Epoch 32/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0262 - mae: 0.0442 - val_loss: 0.0133 - val_mae: 0.0232
Epoch 33/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0276 - mae: 0.0461 - val_loss: 0.0458 - val_mae: 0.0338

In [71]:
ann.save('ann.keras')

In [72]:
import joblib

joblib.dump(scale,'scale.plk')

['scale.plk']